# Generated by Django 2.0.2 on 2018-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luda', '0006_auto_20180306_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.CharField(default='', max_length=9999)),
            ],
        ),
        migrations.RemoveField(
            model_name='gmy',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='my',
            name='update_time',
        ),
    ]
